### ISSUE TITLE
HEOS responded with invalid data.

### ISSUE THREAD

**Issue by meistermopper** [withstu/ioBroker.heos#108]
Hello,

i upgraded js-controller to 3.3.15 und the admin adapter to 5.1.23. As a result, I get the error message sporadically:

<html><body>

2021-09-13 05:36:52.749 | error | [startPlayers] HEOS responded with invalid data.
-- | -- | --

</body>
</html>

In fact all works fine. 
Perhaps there is a possibility to remedy this error.

**Comment by withstu** [comment]
Hi,
the cause of the error message is not the adapter itself and nothing to worry about. In some conditions the heos API is responding with invalid data. Maybe because the heos device has internally some crashed processes. Therefore I've implemented some days ago the auto reboot feature. Whenever the Heos device crashed it gets rebooted. I keept the error message to inform the user, that something with the device is not ok.
Cheers
