### ISSUE TITLE
Denon Home 350 with HEOS not working

### ISSUE THREAD

**Issue by GithubJen** [withstu/ioBroker.heos#72]
Dear Developer,

thanks for developing the HEOS Plugin for IOBroker. I installed it but it seems that it does not support my Denon Home 350 with HEOS. The PLugin does not find the speaker at all. Is it more a technical issue on my side or is the speaker not supported yet?

**Comment by withstu** [comment]
Hey GitHubJen,
I don't know if the adapter work with Denon Home 350 as I don't own one. However the HEOS API didn't change since 2018 so I guess it should work. What you can do is to activate the debug log in the instance view of ioBroker and search for some hints. Please also check if you can reach the Heos player from your ioBroker server (command: telnet PLAYER IP 1255).
Cheers

**Comment by GithubJen** [comment]
@withstu Thanks for your response. I found the issue - iobroker is running in a docker on a Synology NAS but the network setting for the docker container was set to bridge instead of "host". Thats why the upnp response could not be catched by the plugin. Now it is working fine.
